/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const getApiAdminUserIdParams = zod.object({
  id: zod.string().uuid(),
});

export const getApiAdminUserIdResponse = zod.object({
  email: zod.string().email(),
  admin: zod.boolean(),
});

export const postApiPublicAuthLoginBody = zod.object({
  email: zod.string().email(),
  password: zod.string().min(1),
});

export const postApiPublicAuthLoginResponse = zod.object({
  accessToken: zod.string(),
  refreshToken: zod.string(),
});

export const postApiPublicAuthRegisterBody = zod.object({
  email: zod.string().email(),
  password: zod.string().min(1),
});

export const postApiPublicAuthRegisterResponse = zod.object({
  message: zod.string(),
  code: zod.string(),
});

export const postApiPublicAuthRefreshBody = zod.object({
  accessToken: zod.string(),
  refreshToken: zod.string(),
});

export const postApiPublicAuthRefreshResponse = zod.object({
  accessToken: zod.string(),
  refreshToken: zod.string(),
});

export const postApiPublicAuthResetPasswordBody = zod.object({
  token: zod.string(),
  password: zod.string(),
});

export const postApiPublicAuthResetPasswordResponse = zod.object({
  code: zod.string(),
  message: zod.string(),
});

export const postApiPublicAuthResetPasswordRequestBody = zod.object({
  email: zod.string().email(),
});

export const postApiPublicAuthResetPasswordRequestResponse = zod.object({
  message: zod.string(),
  code: zod.string(),
});

export const postApiPublicAuthValidateAccountBody = zod.object({
  token: zod.string().min(1),
});

export const postApiPublicAuthValidateAccountResponse = zod.object({
  message: zod.string(),
  code: zod.string(),
});

export const postApiPublicAuthResendValidationEmailBody = zod.object({
  email: zod.string().email().optional(),
  token: zod.string().optional(),
});

export const postApiPublicAuthResendValidationEmailResponse = zod.object({
  message: zod.string(),
  code: zod.string(),
});

export const getApiPublicHealthcheckResponse = zod.object({
  message: zod.string(),
  timestamp: zod.string(),
  uptime: zod.number(),
});
