version: "3.9"

services:
  postgres:
    container_name: postgres-${PROJECT_NAME:-projectName}
    image: postgres:16
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pass}
      POSTGRES_DB: ${DB_DATABASE:-postgres}
      PGDATA: /var/lib/postgresql/data/db-files/

  redis:
    container_name: redis-${PROJECT_NAME:-projectName}
    image: "redis:7-bullseye"
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: redis
    ports:
      - 9003:6379
    volumes:
      - redis_data:/data

  mailhog:
    container_name: mailhog-${PROJECT_NAME:-projectName}
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    logging:
      driver: none # disable saving logs
    ports:
      - 1025:1025
      - 8025:8025

  adminer:
    container_name: adminer-${PROJECT_NAME:-projectName}
    image: michalhosna/adminer
    restart: unless-stopped
    ports:
      - 8089:8080
    environment:
      ADMINER_DRIVER: pgsql
      ADMINER_SERVER: postgres
      ADMINER_DB: postgres
      ADMINER_USERNAME: postgres
      ADMINER_PASSWORD: pass
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: ${PROJECT_NAME:-Project Name} - local

  pgadmin:
    container_name: pgadmin-${PROJECT_NAME:-projectName}
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5050:80
    restart: unless-stopped

volumes:
  db-data:
  redis_data:
  pgadmin:
