/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const zodPostApiPublicAuthLoginBody = zod.object({
  email: zod.string().email(),
  password: zod.string().min(1)
});

export const zodPostApiPublicAuthLoginResponse = zod.object({
  accessToken: zod.string(),
  refreshToken: zod.string()
});

export const zodPostApiPublicAuthRegisterBody = zod.object({
  email: zod.string().email(),
  password: zod.string().min(1)
});

export const zodPostApiPublicAuthRegisterResponse = zod.object({
  message: zod.string(),
  code: zod.string()
});

export const zodPostApiPublicAuthRefreshBody = zod.object({
  accessToken: zod.string(),
  refreshToken: zod.string()
});

export const zodPostApiPublicAuthRefreshResponse = zod.object({
  accessToken: zod.string(),
  refreshToken: zod.string()
});

export const zodPostApiPublicAuthResetPasswordBody = zod.object({
  token: zod.string(),
  password: zod.string()
});

export const zodPostApiPublicAuthResetPasswordResponse = zod.object({
  code: zod.string(),
  message: zod.string()
});

export const zodPostApiPublicAuthResetPasswordRequestBody = zod.object({
  email: zod.string().email()
});

export const zodPostApiPublicAuthResetPasswordRequestResponse = zod.object({
  message: zod.string(),
  code: zod.string()
});

export const zodPostApiPublicAuthValidateAccountBody = zod.object({
  token: zod.string().min(1)
});

export const zodPostApiPublicAuthValidateAccountResponse = zod.object({
  message: zod.string(),
  code: zod.string()
});

export const zodPostApiPublicAuthResendValidationEmailBody = zod.object({
  email: zod.string().email().optional(),
  token: zod.string().optional()
});

export const zodPostApiPublicAuthResendValidationEmailResponse = zod.object({
  message: zod.string(),
  code: zod.string()
});

export const zodGetApiPublicHealthcheckResponse = zod.object({
  message: zod.string(),
  timestamp: zod.string(),
  uptime: zod.number()
});
