/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const zodGetApiAdminUserIdParams = zod.object({
  id: zod.string().uuid()
});

export const zodGetApiAdminUserIdResponse = zod.object({
  email: zod.string().email(),
  admin: zod.boolean()
});
