/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Starter API
 * OpenAPI spec version: 1.0.0
 */

import type { AxiosRequestConfig, AxiosResponse, AxiosInstance } from 'axios';
import type { UserGetById200 } from '.././models';

export const getAdminApiCollection = (axios: AxiosInstance) => {
  const userGetById = <TData = AxiosResponse<UserGetById200>>(id: string, options?: AxiosRequestConfig): Promise<TData> => {
    return axios.get(`/api/admin/user/${id}`, options);
  };
  return { userGetById };
};
export type UserGetByIdResult = AxiosResponse<UserGetById200>;
