/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiPublicAuthRegisterBody = {
  email: string;
  /** @minLength 1 */
  password: string;
};
