/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

import type { AxiosRequestConfig, AxiosResponse, AxiosInstance } from 'axios';
import type { GetApiAdminUserId200 } from './index.schemas';

export const getAdminApi = (axios: AxiosInstance) => {
  const getUserId = <TData = AxiosResponse<GetApiAdminUserId200>>(id: string, options?: AxiosRequestConfig): Promise<TData> => {
    return axios.get(`/api/admin/user/${id}`, options);
  };
  return { getUserId };
};
export type GetUserIdResult = AxiosResponse<GetApiAdminUserId200>;
