/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
export type PostApiPublicAuthResendValidationEmailBody = {
  email?: string;
  token?: string;
};

export type PostApiPublicAuthValidateAccountBody = {
  /** @minLength 1 */
  token: string;
};

export type PostApiPublicAuthResetPasswordRequestBody = {
  email: string;
};

export type PostApiPublicAuthResetPasswordBody = {
  password: string;
  token: string;
};

export type PostApiPublicAuthRefreshBody = {
  accessToken: string;
  refreshToken: string;
};

export type PostApiPublicAuthRegisterBody = {
  email: string;
  /** @minLength 1 */
  password: string;
};

export type PostApiPublicAuthLoginBody = {
  email: string;
  /** @minLength 1 */
  password: string;
};

export type GetApiAdminUserId200 = {
  admin: boolean;
  email: string;
};

export interface HealthcheckResponse {
  message: string;
  timestamp: string;
  uptime: number;
}

export interface ResetPasswordResponse {
  code: string;
  message: string;
}

export interface RefreshTokens {
  accessToken: string;
  refreshToken: string;
}

export interface LoginTokens {
  accessToken: string;
  refreshToken: string;
}

export interface ErrorResponse {
  code: string;
  message: string;
}
